export enum WalletCategory {
  Exchange = "exchange",
  Foundation = "foundation", 
  Investor = "investor",
  Team = "team",
  Community = "community",
  Dex = "dex",
  Infrastructure = "infrastructure",
  MarketMaker = "market_maker",
}

export const CEX_KEYWORDS = [
  "binance",
  "coinbase",
  "kraken",
  "okx",
  "bybit",
  "bitfinex",
  "kucoin",
  "mexc",
  "gate.io",
  "gate io",
  "huobi",
  "upbit",
  "ftx",
  "bitstamp",
  "bitget",
  "crypto.com",
  "cryptocom",
  "gemini",
  "poloniex",
  "bittrex",
  "cex.io",
  "bitvavo",
];

// Decentralized exchanges / AMMs / Pools (DEX) — on-chain venues
export const DEX_KEYWORDS = [
  "meteora",
  "dlmm",
  "clmm",
  "whirlpool",
  "pool",
  "liquidity pool",
  "liquidity provider",
  "lp",
  "amm",
  "raydium",
  "orca",
  "openbook",
  "serum",
  "phoenix",
  "kamino",
  "lifinity",
  "crema",
  "saros",
  "saber",
  "cykura",
  "jupiter", // aggregator; many pool labels still show underlying AMM
  "drift",
  "mango",
  "zeta", // perps/margin DEXs (may hold custodied assets on-chain)
  "aldrin",
  "mercurial",
  "marinade",
  "solend",
  "francium",
  "tulip",
  "port finance",
  "larix",
  "apricot",
  "dex",
  "swap",
  "automated market maker",
];



export enum AccountType {
  CEX = 'cex',
  DEX = 'dex', 
  DEFI_PROTOCOL = 'defi_protocol',
  BRIDGE = 'bridge',
  STAKING = 'staking',
  NFT_MARKETPLACE = 'nft_marketplace',
  VALIDATOR = 'validator',
  PROGRAM_AUTHORITY = 'program_authority',
  MARKET_MAKER = 'market_maker',
  WHALE = 'whale',
  BOT_TRADER = 'bot_trader',
  INSTITUTIONAL = 'institutional',
  UNKNOWN = 'unknown'
}
